app/Repositories/TeamRepository.php
app/Teams/Invitation.php

Javascript expects a token field to be received on the invitation object on the registration views. Unhide the token field from the model and fix syntax errors in the method to attach a user to a team.

Fixes invitations

---

app/Console/Install.php

This fixes #25 by checking if the .env file exists before trying to fetch its content.

Fix: #25 .env file not found on new install.

---

app/Http/Controllers/Auth/AuthController.php
app/InteractsWithSparkHooks.php

* The callCustomValidator method wasn't using `call_user_func_array`
* The AuthController was looking for the wrong custom registration validator 
* The AuthController had no `InteractsWithSparkHooks` trait

Fixed callCustomValidator and $validateRegistrationsWith closure calls

---

resources/stubs/config/app.php

If spark is meant for fresh 5.1 installations, the Authorize service provider and Gate facade should be included.

Register The AuthServiceProvider & Gate Facade

---

resources/assets/sass/spark.scss

The footer height wasn’t extending to bottom of page responsively. When viewing page responsively it was leaving a white background below the social icons. I have updated the footer to include a min-height of 80px, rather than height.
Here's what it was doing:

Make footer min-height

---

resources/stubs/database/migrations/2014_10_12_200000_create_teams_tables.php

fixes an Integrity constraint violation when trying to add/create a team. (This may only affect sqlite? I don't think so though)

set `team->owner_id` as nullable.

---

app/Console/Install.php

As the `config\app.php` file is overwritten during the Spark install, the key will need to be re-generated. Is this usually done for people when running `laravel new {project}`.

Create encryption key during Spark install

---

.gitattributes

Ensure Sparkl remains referenced as a PHP project on Github

Ensure Sparkl remains referenced as a PHP project on Github

---

app/Http/Controllers/Settings/SubscriptionController.php
app/Spark.php

This introduces a new `Spark::$swapSubscriptionsWith` callback that can be used when a user switches their plan, rather than Cashier’s built-in.

Custom callback for subscription swapping

---

app/Contracts/Repositories/UserRepository.php
app/Http/Controllers/Settings/SubscriptionController.php
app/Repositories/UserRepository.php
app/Spark.php

I added a `createSubscriptionsWith` callback to Stripe.
This allows to modify the Stripe customer creation - for example if you want to pass additional Stripe metadata.
This also removes the duplicate subscription creation within the `SubscriptionController`.

Allow usage of a "createSubscriptionsWith" callback

---

app/Teams/CanJoinTeams.php

When an existing user is invited, the role column on the pivot tabel remained empty, thus making the "Settings - Membership" page fail to render (because the Vue role filter complained about not being able to find the .text property of undefined). This fix properly sets the default role.

Fix invitations for existing users

---

resources/assets/js/settings/team/membership.js

everythingIsLoaded has to depend on the roles array being filled, otherwise there are occasions where roles aren't loaded before the page displays. This results in a blank membership page because the role filter throws an error.

fix-everythingIsLoaded-membership

---

app/Repositories/TeamRepository.php

Hello,
While trying to create a team using PostgresSql, I get an error :
```
SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "owner_id" violates not-null constraint
DETAIL: Failing row contains (13, null, Test, 2015-10-08 14:54:28, 2015-10-08 14:54:28). (SQL: insert into "teams" ("name", "updated_at", "created_at") values (Test, 2015-10-08 14:54:28, 2015-10-08 14:54:28) returning "id")
```
PostgresSQL is strongly enforcing schema rules, so it fails when trying to create a new team without specifying the owner_id  as below : 
```
public function create($user, array $data)
{
$team = $user->teams()->create(
['name' => $data['name']], ['role' => 'owner']
);
$team->owner_id = $user->id;
$team->save();
return $team;
}
```
As the owner_id is not fillable on the Team model, I …

Error while creating a team using PostgresSQL

---

resources/stubs/resources/assets/sass/app.scss

gulp sass pre-compilation breaks because these files are not copied to the application during install.

fix import path

---

resources/assets/sass/spark.scss

This is a small CSS fix for the `.footer` class. I changed it's position value from `absolute` to `fixed`, because it's causing a layout issue on bigger content. If the content is higher than the screen, when scrolling, the footer gets stuck at the top, and not as it should, on the bottom of the page. Here is a screenshot of the issue:

Fix for overlapping footer on content

---

resources/assets/js/core/dependencies.js

E.g. `window.$ = window.jQuery = require('jquery')` nullifies all jquery extensions.
`... = require('underscore')` - same here, any mixins will be thrown away. Also someone may be using lodash or another underscorish library.

Fix global libraries override

---

app/Teams/CanJoinTeams.php

This method could be useful if you want to restrict certain methods to the team owner.

Add ownedTeams method to CanJoinTeams trait

---

app/Http/routes.php

Due to [Middleware being separated into groups in 5.2](https://github.com/laravel/laravel/commit/587e514719f11a4f146266d82b28be971e6af34f) the `/login` route or any other that does validation would error:
```
ErrorException (E_ERROR)
Undefined variable: errors  
(View: /home/vagrant/sites/52spark/vendor/laravel/spark/resources/views/common/error-alert.blade.php)
```
This may not be the most elegant solution but it follows the example style in the the [5.2 routes.php file](https://github.com/laravel/laravel/blob/master/app/Http/routes.php#L29).

Routes defined in 5.2 middleware groups

---

app/Http/routes.php

Not sure how I missed these on [the initial change](https://github.com/laravel/spark/pull/164). But after #167 and further investigation [almost](https://github.com/laravel/spark/blob/master/app/Http/Controllers/API/TeamController.php#L31) [all](https://github.com/laravel/spark/blob/master/app/Http/Controllers/API/SubscriptionController.php#L24) `spark/api/...` routes rely on the `auth` middleware which relies on Session store. 
Building up from the base 'api' middleware group, this is the minimum to make these routes work:
```
'api' => [
\App\Http\Middleware\EncryptCookies::class,
\Illuminate\Session\Middleware\StartSession::class,
\App\Http\Middleware\VerifyCsrfToken::class,
'throttle:60,1',
],
```
Without those $this->auth->guest() returns false or throws an error.
Possible approaches …

spark/api/... routes now in 'web' middleware group.

---

resources/views/settings/tabs/security/two-factor.blade.php

On the `/settings` page, the Authy link is basically invisible:
Per [Bootstrap's alert component](http://getbootstrap.com/components/#alerts-links), links should have `alert-link` class.
Result:

Two factor alert link now has 'alert-link' class

---

resources/views/auth/registration/subscription/billing.blade.php

After selecting a plan, then clicking "Change Plan", the selected plan is set to null, which causes Vue to console log:
`[Vue warn]: Error when evaluating expression "selectedPlan.trialDays". Turn on debug mode to see stack trace.`
This fixes that.

Fix Vue error when changing selected plan

---

app/Console/Install.php

Altered the search+replace in updateAuthConfig() to reflect new default ("auth.emails.password") in an out-of-the-box Laravel 5.2 install, as per laravel/spark#181

Fix password reset email template for Laravel 5.2

---

composer.json

dompdf is required to generate the invoices and is not currently required in the spark composer, I have added the PR just for convenience.

Add dompdf dependancy

---

resources/stubs/package.json

reverts #194 which bumped bootstrap instead of Laravel Elixir which [has a v4.0 release](https://github.com/laravel/elixir/releases) while bootstrap does not.

fix PR 194 - bump laravel elixir version

---

readme.md

Add a note to the README that installing Spark should be done while crafting your app, since doing so after doing large changes like renaming your app's namespace can result in errors while installing Spark.
Close #131

Add a note about installing Spark
